### ISSUE TITLE
H-05-03: Como un usuario necesito realizar reservas, con la finalidad de poder hacer reservas de una mesa en el restaurante elegido

### ISSUE THREAD

**Issue by alejandraGM** [topx777/MaskhayPlace#4]
- [x] Realizar el formulario de reserva

- [x] Realizar la funcionalidad de reserva

**Comment by topx777** [comment]
Formulario de reserva concluido y diseñado, solo falta la funcionalidad y la parte de la programación para que los usuarios puedan realizar reservas de un restaurante

**Comment by topx777** [comment]
me equivoque sin querer lo cerre

**Comment by topx777** [comment]
Diseno de reservas finalizado y funcionamiento, tarea finalizada
