### ISSUE TITLE
H-05-05: Como un usuario necesito poder ver los medicamentos en oferta, con el fin de conocer la informacion detallada de los medicamentos que se encuentran en oferta

### ISSUE THREAD

**Issue by alejandraGM** [topx777/MaskhayPlace#6]
- [x] Realizar el diseño de la tabla de productos en oferta de la farmacia con sus caracteristicas

- [x] Realizar el funcionamiento y programacion de los productos en oferta

**Comment by topx777** [comment]
Tarea completada
