### ISSUE TITLE
H-05-06: Como un usuario necesito ver las calificaciones del lugar, con el fin de poder realizar las calificaciones del mismo

### ISSUE THREAD

**Issue by alejandraGM** [topx777/MaskhayPlace#7]
- [x] Realizar la opcion de calificacion por puntaje

- [x] Realizar el diseño del formulario de comentario

- [x] Realizar el funcionamiento de calificaciones de lugar

**Comment by topx777** [comment]
Realizado el diseño del formulario de calificacion y los detalles y calificaciones del lugar, aun falta la funcionalidad de que un usuario pueda realizar la calificacion y el comentario de un lugar, osea la funcionalidad y la programación del mismo

**Comment by topx777** [comment]
Tarea de funcionamiento realizado con exito, historia de usuario completada.
